"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, ChevronRight, CircleHelp, LockKeyhole, MessageCircle, Play, ShieldCheck, ShoppingBag, Sparkles, X, Zap } from "lucide-react";

type Step = "shop" | "whatsapp" | "consent" | "message";

const steps: { id: Step; title: string; caption: string; icon: typeof ShoppingBag }[] = [
  { id: "shop", title: "TikTok Shop", caption: "Authorize seller account", icon: ShoppingBag },
  { id: "whatsapp", title: "WhatsApp Business", caption: "Connect verified number", icon: MessageCircle },
  { id: "consent", title: "Customer consent", caption: "Choose an opt-in flow", icon: ShieldCheck },
  { id: "message", title: "Order message", caption: "Create a useful update", icon: Sparkles },
];

export default function ShopAutomationPage() {
  const [step, setStep] = useState<Step>("shop");
  const [done, setDone] = useState<Partial<Record<Step, boolean>>>({});
  const [optIn, setOptIn] = useState(1);
  const [active, setActive] = useState(false);
  const [help, setHelp] = useState(false);
  const [message, setMessage] = useState("Hi {{first_name}}, thanks for your TikTok Shop order {{order_id}}. We’ll keep you updated here. Reply STOP to opt out.");
  const index = steps.findIndex((item) => item.id === step);
  const progress = Object.values(done).filter(Boolean).length * 25;
  const advance = () => { setDone((value) => ({ ...value, [step]: true })); if (steps[index + 1]) setStep(steps[index + 1].id); };

  return <main className="min-h-screen bg-[#f7f8f8] text-[#17201d]">
    <header className="border-b border-black/[.08] bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8">
      <Link href="/" className="flex items-center gap-2.5 font-black tracking-[-.045em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#17201d] text-xs text-white">TL</span>TickLoop <span className="hidden rounded-full bg-[#eff7ef] px-2 py-0.5 text-[10px] uppercase tracking-widest text-[#2b7843] sm:inline">Beta</span></Link>
      <button onClick={() => setHelp(true)} className="flex items-center gap-2 text-sm font-bold text-[#51605a]"><CircleHelp className="h-4 w-4"/> Help</button>
    </div></header>
    <div className="mx-auto max-w-7xl px-5 py-9 sm:px-8 sm:py-12">
      <section className="mb-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-2 text-xs font-black uppercase tracking-[.16em] text-[#2b7843]">TikTok Shop × WhatsApp</p><h1 className="max-w-2xl text-4xl font-black tracking-[-.06em] sm:text-5xl">Turn every new order into a helpful conversation.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#65706b] sm:text-base">Connect your shop, choose a consent-first workflow, and send buyers the updates they expect.</p></div>
        <div className="rounded-2xl border border-[#dce4de] bg-white px-5 py-4"><p className="text-xs font-bold uppercase tracking-widest text-[#68736d]">Setup progress</p><p className="mt-1 text-2xl font-black">{progress}% <span className="text-sm font-medium text-[#78817d]">complete</span></p><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#edf1ee]"><div className="h-full bg-[#2b7843] transition-all" style={{ width: `${progress}%` }}/></div></div>
      </section>
      <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-[#dce4de] bg-white p-4 shadow-[0_12px_45px_rgba(18,42,28,.05)] sm:p-7"><div className="mb-8 grid gap-2 sm:grid-cols-4">{steps.map((item, number) => { const Icon = item.icon; const selected = step === item.id; return <button key={item.id} onClick={() => setStep(item.id)} className={`flex items-center gap-3 rounded-2xl p-3 text-left ${selected ? "bg-[#17201d] text-white" : "hover:bg-[#f4f7f5]"}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-xl ${selected ? "bg-white/15" : done[item.id] ? "bg-[#dff3e4] text-[#2b7843]" : "bg-[#f0f3f1] text-[#78827d]"}`}>{done[item.id] ? <Check className="h-4 w-4"/> : <Icon className="h-4 w-4"/>}</span><span><span className="block text-xs font-bold">{number + 1}. {item.title}</span><span className={`hidden text-[11px] sm:block ${selected ? "text-white/55" : "text-[#78817d]"}`}>{item.caption}</span></span></button>; })}</div>
        {step === "shop" && <Panel tag="Step 1 of 4" title="Connect your TikTok Shop" copy="Securely authorize your seller account. TickLoop uses official TikTok Shop permissions, never your Seller Center password."><div className="rounded-2xl border border-[#e1e7e3] bg-[#fbfcfb] p-5"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-black text-lg font-black text-white">♪</span><div><p className="font-bold">TikTok Shop Seller Center</p><p className="mt-1 text-sm leading-5 text-[#68736d]">Approve access to order events, delivery status, and webhooks.</p></div></div><Action onClick={advance}>Connect TikTok Shop</Action></div><Notice>Buyer contact details can be masked based on market and shipping method. We only process the fields returned by the official API.</Notice></Panel>}
        {step === "whatsapp" && <Panel tag="Step 2 of 4" title="Connect WhatsApp Business" copy="Use your verified WhatsApp Business account to send official customer updates. Your personal WhatsApp stays separate."><div className="grid gap-3 sm:grid-cols-2"><Card title="Already use WhatsApp Business?" copy="Link your existing account through Meta’s secure signup."/><Card title="Need a business account?" copy="We’ll guide you through a business profile and number verification."/></div><Action onClick={advance}>Connect WhatsApp Business</Action></Panel>}
        {step === "consent" && <Panel tag="Step 3 of 4" title="Choose how buyers opt in" copy="A delivery phone number is not automatically permission for marketing. Choose a clear way buyers can agree to WhatsApp updates."><div className="grid gap-3">{[["Buyer starts the chat", "Add a WhatsApp link or QR code to your order card and package."], ["Post-purchase opt-in", "Ask buyers to agree before receiving WhatsApp updates and save the record."]].map(([title, copy], i) => <button onClick={() => setOptIn(i)} key={title} className={`rounded-2xl border p-5 text-left ${optIn === i ? "border-[#2b7843] bg-[#f1faf3] ring-1 ring-[#2b7843]" : "border-[#e1e7e3]"}`}><span className="flex gap-3"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border ${optIn === i ? "border-[#2b7843] bg-[#2b7843] text-white" : "border-[#c8d0cb]"}`}>{optIn === i && <Check className="h-3.5 w-3.5"/>}</span><span><b>{title}</b><span className="mt-1 block text-sm leading-5 text-[#68736d]">{copy}</span></span></span></button>)}</div><Action onClick={advance}>Save consent method</Action></Panel>}
        {step === "message" && <Panel tag="Step 4 of 4" title="Create your first order update" copy="Utility templates are for helpful, expected updates. Customers can reply and opt out at any time."><label className="text-sm font-bold">New order confirmation</label><textarea value={message} onChange={(e) => setMessage(e.target.value)} rows={5} className="mt-2 w-full rounded-2xl border border-[#dbe3de] bg-[#fcfdfc] p-4 text-sm leading-6 outline-none focus:border-[#2b7843]"/><p className="mt-2 text-xs text-[#78817d]">Variables: <code className="rounded bg-[#eff3f0] px-1.5 py-0.5">{"{{first_name}}"}</code> <code className="rounded bg-[#eff3f0] px-1.5 py-0.5">{"{{order_id}}"}</code></p><Action onClick={() => { setDone((v) => ({ ...v, message: true })); setActive(true); }}>Activate automation</Action></Panel>}
      </section>
      <aside className="space-y-4"><div className="rounded-3xl bg-[#17201d] p-6 text-white shadow-xl"><div className="mb-7 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-widest text-white/55">Live automation</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-widest ${active ? "bg-[#3ca35a]" : "bg-white/10 text-white/60"}`}>{active ? "Active" : "Not active"}</span></div><Flow icon={ShoppingBag} title="New TikTok Shop order" detail="Order paid" ready={Boolean(done.shop)}/><Line/><Flow icon={ShieldCheck} title="Consent check" detail={done.consent ? "Opt-in saved" : "Required before sending"} ready={Boolean(done.consent)}/><Line/><Flow icon={MessageCircle} title="WhatsApp template" detail={active ? "Send confirmation" : "Waiting for setup"} ready={active}/><button disabled={!active} onClick={() => setHelp(true)} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#17201d] disabled:opacity-40"><Play className="h-4 w-4 fill-current"/> Send test event</button></div><div className="rounded-3xl border border-[#dce4de] bg-white p-5"><div className="flex gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-[#2b7843]"/><div><p className="text-sm font-bold">Built around permission</p><p className="mt-1 text-xs leading-5 text-[#68736d]">Consent records, template approvals, delivery, and STOP requests belong in every automation.</p></div></div><button onClick={() => setHelp(true)} className="mt-4 flex items-center gap-1 text-xs font-bold text-[#2b7843]">Learn the basics <ChevronRight className="h-3.5 w-3.5"/></button></div></aside></div>
    </div>
    {help && <div className="fixed inset-0 z-50 grid place-items-center bg-[#17201d]/40 p-5"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eff7ef] text-[#2b7843]"><Zap className="h-5 w-5"/></span><button onClick={() => setHelp(false)}><X className="h-5 w-5"/></button></div><h2 className="mt-5 text-xl font-black">Ready for the connection layer</h2><p className="mt-2 text-sm leading-6 text-[#68736d]">This live prototype guides onboarding. TikTok OAuth, Meta signup, consent records, and verified webhooks are the next production integration phase.</p><button onClick={() => setHelp(false)} className="mt-6 w-full rounded-xl bg-[#17201d] py-3 text-sm font-bold text-white">Got it</button></div></div>}
  </main>;
}
function Panel({ tag, title, copy, children }: { tag: string; title: string; copy: string; children: React.ReactNode }) { return <div><p className="text-xs font-black uppercase tracking-[.14em] text-[#2b7843]">{tag}</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em] sm:text-3xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#68736d]">{copy}</p><div className="mt-7">{children}</div></div>; }
function Action({ onClick, children }: { onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#2b7843] px-4 py-3 text-sm font-bold text-white transition hover:bg-[#17201d]">{children} <ArrowRight className="h-4 w-4"/></button>; }
function Notice({ children }: { children: React.ReactNode }) { return <div className="mt-5 rounded-2xl border border-[#d9eadc] bg-[#f1faf3] p-4 text-xs leading-5 text-[#41644b]">{children}</div>; }
function Card({ title, copy }: { title: string; copy: string }) { return <div className="rounded-2xl border border-[#e1e7e3] p-5"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-[#68736d]">{copy}</p></div>; }
function Flow({ icon: Icon, title, detail, ready }: { icon: typeof ShoppingBag; title: string; detail: string; ready: boolean }) { return <div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${ready ? "bg-[#2b7843]" : "bg-white/10"}`}><Icon className="h-4 w-4"/></span><span><b className="block text-sm">{title}</b><span className="block text-xs text-white/50">{detail}</span></span></div>; }
function Line() { return <div className="ml-5 h-4 border-l border-dashed border-white/20"/>; }
