// AUTO-GENERATED by scripts/sync-fathopes-media.mjs — do not edit by hand.
// Re-run: node scripts/sync-fathopes-media.mjs

export interface FathopesMediaItem {
  src: string;
  thumb: string;
  ratio: number;
  category: string;
  catSlug: string;
  type: "image" | "video";
  png: boolean;
  name: string;
}

export interface FathopesCategory {
  label: string;
  slug: string;
  count: number;
}

export const FATHOPES_TOTAL = 326;

export const FATHOPES_CATEGORIES: FathopesCategory[] = [
  {
    "label": "Super Hero",
    "slug": "super-hero",
    "count": 21
  },
  {
    "label": "Images",
    "slug": "images",
    "count": 10
  },
  {
    "label": "Strand Mall",
    "slug": "strand-mall",
    "count": 40
  },
  {
    "label": "Wisma CIMB Bangsar 2025",
    "slug": "wisma-cimb-bangsar-2025",
    "count": 29
  },
  {
    "label": "Ranger Training",
    "slug": "ranger-training",
    "count": 33
  },
  {
    "label": "Team Building",
    "slug": "team-building",
    "count": 147
  },
  {
    "label": "Waste2Energy",
    "slug": "waste2energy",
    "count": 4
  },
  {
    "label": "Astro",
    "slug": "astro",
    "count": 3
  },
  {
    "label": "PLUS Community Day",
    "slug": "plus-community-day",
    "count": 1
  },
  {
    "label": "Mitsui X FatHopes Energy",
    "slug": "mitsui-x-fathopes-energy",
    "count": 1
  },
  {
    "label": "KLB Fuel",
    "slug": "klb-fuel",
    "count": 1
  },
  {
    "label": "My Aero 2026",
    "slug": "my-aero-2026",
    "count": 1
  },
  {
    "label": "Turiya Earth Day 2026",
    "slug": "turiya-earth-day-2026",
    "count": 1
  },
  {
    "label": "FatHopes Loyalty App",
    "slug": "fathopes-loyalty-app",
    "count": 21
  },
  {
    "label": "Bunting",
    "slug": "bunting",
    "count": 1
  },
  {
    "label": "Corporate Asset",
    "slug": "corporate-asset",
    "count": 9
  },
  {
    "label": "Brand Video",
    "slug": "brand-video",
    "count": 1
  },
  {
    "label": "AI Video",
    "slug": "ai-video",
    "count": 1
  },
  {
    "label": "FatHopes Vendor App",
    "slug": "fathopes-vendor-app",
    "count": 1
  }
];

export const FATHOPES_MEDIA: FathopesMediaItem[] = [
  {
    "src": "/fathopes/super-hero/d-r-up-action.png",
    "thumb": "/fathopes/_thumbs/super-hero/d-r-up-action.webp",
    "ratio": 0.974,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "D.R. UP-Action.png"
  },
  {
    "src": "/fathopes/super-hero/d-r-up-back.png",
    "thumb": "/fathopes/_thumbs/super-hero/d-r-up-back.webp",
    "ratio": 0.46,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "D.R. UP-Back.png"
  },
  {
    "src": "/fathopes/super-hero/d-r-up-front.png",
    "thumb": "/fathopes/_thumbs/super-hero/d-r-up-front.webp",
    "ratio": 0.546,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "D.R. UP-Front.png"
  },
  {
    "src": "/fathopes/super-hero/d-r-up-left.png",
    "thumb": "/fathopes/_thumbs/super-hero/d-r-up-left.webp",
    "ratio": 0.25,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "D.R. UP-Left.png"
  },
  {
    "src": "/fathopes/super-hero/d-r-up-right.png",
    "thumb": "/fathopes/_thumbs/super-hero/d-r-up-right.webp",
    "ratio": 0.308,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "D.R. UP-Right.png"
  },
  {
    "src": "/fathopes/super-hero/glinciro-action.png",
    "thumb": "/fathopes/_thumbs/super-hero/glinciro-action.webp",
    "ratio": 0.814,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Glinciro -Action.png"
  },
  {
    "src": "/fathopes/super-hero/glinciro-2.png",
    "thumb": "/fathopes/_thumbs/super-hero/glinciro-2.webp",
    "ratio": 0.354,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Glinciro 2.png"
  },
  {
    "src": "/fathopes/super-hero/glinciro-3.png",
    "thumb": "/fathopes/_thumbs/super-hero/glinciro-3.webp",
    "ratio": 0.276,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Glinciro 3.png"
  },
  {
    "src": "/fathopes/super-hero/glinciro-4.png",
    "thumb": "/fathopes/_thumbs/super-hero/glinciro-4.webp",
    "ratio": 0.342,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Glinciro 4.png"
  },
  {
    "src": "/fathopes/super-hero/glinciro-5.png",
    "thumb": "/fathopes/_thumbs/super-hero/glinciro-5.webp",
    "ratio": 0.352,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Glinciro 5.png"
  },
  {
    "src": "/fathopes/super-hero/kit-2.png",
    "thumb": "/fathopes/_thumbs/super-hero/kit-2.webp",
    "ratio": 0.472,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Kit 2.png"
  },
  {
    "src": "/fathopes/super-hero/kit-3.png",
    "thumb": "/fathopes/_thumbs/super-hero/kit-3.webp",
    "ratio": 0.378,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Kit 3.png"
  },
  {
    "src": "/fathopes/super-hero/kit-4.png",
    "thumb": "/fathopes/_thumbs/super-hero/kit-4.webp",
    "ratio": 0.336,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Kit 4.png"
  },
  {
    "src": "/fathopes/super-hero/kit-action.png",
    "thumb": "/fathopes/_thumbs/super-hero/kit-action.webp",
    "ratio": 0.926,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Kit-Action.png"
  },
  {
    "src": "/fathopes/super-hero/sparron-2.png",
    "thumb": "/fathopes/_thumbs/super-hero/sparron-2.webp",
    "ratio": 0.392,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Sparron 2.png"
  },
  {
    "src": "/fathopes/super-hero/sparron-3.png",
    "thumb": "/fathopes/_thumbs/super-hero/sparron-3.webp",
    "ratio": 0.304,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Sparron 3.png"
  },
  {
    "src": "/fathopes/super-hero/sparron-4.png",
    "thumb": "/fathopes/_thumbs/super-hero/sparron-4.webp",
    "ratio": 0.3,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Sparron 4.png"
  },
  {
    "src": "/fathopes/super-hero/sparron-5.png",
    "thumb": "/fathopes/_thumbs/super-hero/sparron-5.webp",
    "ratio": 0.338,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Sparron 5.png"
  },
  {
    "src": "/fathopes/super-hero/sparron-action.png",
    "thumb": "/fathopes/_thumbs/super-hero/sparron-action.webp",
    "ratio": 0.678,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Sparron-Action.png"
  },
  {
    "src": "/fathopes/super-hero/superheroes-group-02.png",
    "thumb": "/fathopes/_thumbs/super-hero/superheroes-group-02.webp",
    "ratio": 0.706,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Superheroes group-02.png"
  },
  {
    "src": "/fathopes/super-hero/superheroes-group.png",
    "thumb": "/fathopes/_thumbs/super-hero/superheroes-group.webp",
    "ratio": 1,
    "category": "Super Hero",
    "catSlug": "super-hero",
    "type": "image",
    "png": true,
    "name": "Superheroes group.png"
  },
  {
    "src": "/fathopes/images/img-4426.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4426.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4426.JPG"
  },
  {
    "src": "/fathopes/images/img-4447.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4447.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4447.jpg"
  },
  {
    "src": "/fathopes/images/img-4454.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4454.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4454.jpg"
  },
  {
    "src": "/fathopes/images/img-4467.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4467.webp",
    "ratio": 0.562,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4467.jpg"
  },
  {
    "src": "/fathopes/images/img-4504.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4504.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4504.jpg"
  },
  {
    "src": "/fathopes/images/img-4866.jpg",
    "thumb": "/fathopes/_thumbs/images/img-4866.webp",
    "ratio": 0.562,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_4866.jpg"
  },
  {
    "src": "/fathopes/images/img-5249.jpg",
    "thumb": "/fathopes/_thumbs/images/img-5249.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_5249.jpg"
  },
  {
    "src": "/fathopes/images/img-5406.jpg",
    "thumb": "/fathopes/_thumbs/images/img-5406.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_5406.jpg"
  },
  {
    "src": "/fathopes/images/img-5417.jpg",
    "thumb": "/fathopes/_thumbs/images/img-5417.webp",
    "ratio": 0.75,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "IMG_5417.jpg"
  },
  {
    "src": "/fathopes/images/pux08219.jpg",
    "thumb": "/fathopes/_thumbs/images/pux08219.webp",
    "ratio": 1.778,
    "category": "Images",
    "catSlug": "images",
    "type": "image",
    "png": false,
    "name": "PUX08219.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3931.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3931.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3931.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3936.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3936.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3936.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3940.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3940.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3940.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3941.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3941.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3941.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3953.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3953.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3953.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3954.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3954.webp",
    "ratio": 1.334,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3954.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3955.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3955.webp",
    "ratio": 1.334,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3955.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3956.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3956.webp",
    "ratio": 1.334,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3956.JPG"
  },
  {
    "src": "/fathopes/strand-mall/img-3957.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/img-3957.webp",
    "ratio": 0.75,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "IMG_3957.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03638.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03638.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03638.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03774.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03774.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03774.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03779.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03779.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03779.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03813.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03813.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03813.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03822.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03822.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03822.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03844.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03844.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03844.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03866.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03866.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03866.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03874.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03874.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03874.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03900.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03900.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03900.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03912.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03912.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03912.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03914.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03914.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03914.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03923.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03923.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03923.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03950.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03950.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03950.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03951.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03951.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03951.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03959.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03959.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03959.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03966.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03966.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03966.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03967.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03967.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03967.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03969.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03969.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03969.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03970.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03970.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03970.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03980.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03980.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03980.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03987.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03987.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03987.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03993.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03993.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03993.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03996.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03996.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03996.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux03998.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux03998.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX03998.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04009.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04009.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04009.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04011.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04011.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04011.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04015.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04015.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04015.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04021.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04021.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04021.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04023.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04023.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04023.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04031.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04031.webp",
    "ratio": 1.778,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04031.JPG"
  },
  {
    "src": "/fathopes/strand-mall/pux04042.jpg",
    "thumb": "/fathopes/_thumbs/strand-mall/pux04042.webp",
    "ratio": 0.562,
    "category": "Strand Mall",
    "catSlug": "strand-mall",
    "type": "image",
    "png": false,
    "name": "PUX04042.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux02960.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux02960.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX02960.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux02974.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux02974.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX02974.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03014.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03014.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03014.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03015.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03015.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03015.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03019.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03019.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03019.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03034.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03034.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03034.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03076.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03076.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03076.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03087.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03087.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03087.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03102.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03102.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03102.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03129.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03129.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03129.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03155.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03155.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03155.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03167.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03167.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03167.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03176.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03176.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03176.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03187.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03187.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03187.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03199.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03199.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03199.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03204.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03204.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03204.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03226.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03226.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03226.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03267.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03267.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03267.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03287.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03287.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03287.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03314.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03314.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03314.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03320.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03320.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03320.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03365.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03365.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03365.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03369.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03369.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03369.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03406.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03406.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03406.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03420.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03420.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03420.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03473.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03473.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03473.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03477.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03477.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03477.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03492.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03492.webp",
    "ratio": 1.778,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03492.JPG"
  },
  {
    "src": "/fathopes/wisma-cimb-bangsar-2025/pux03497.jpg",
    "thumb": "/fathopes/_thumbs/wisma-cimb-bangsar-2025/pux03497.webp",
    "ratio": 0.562,
    "category": "Wisma CIMB Bangsar 2025",
    "catSlug": "wisma-cimb-bangsar-2025",
    "type": "image",
    "png": false,
    "name": "PUX03497.JPG"
  },
  {
    "src": "/fathopes/ranger-training/pux05750.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05750.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05750.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05757.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05757.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05757.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05760.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05760.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05760.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05769.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05769.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05769.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05782.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05782.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05782.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05783.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05783.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05783.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05784.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05784.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05784.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05787.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05787.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05787.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05788.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05788.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05788.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05801.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05801.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05801.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05802.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05802.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05802.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05829.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05829.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05829.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05836.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05836.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05836.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05840.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05840.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05840.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05850.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05850.webp",
    "ratio": 0.562,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05850.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05855.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05855.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05855.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05856.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05856.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05856.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05860.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05860.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05860.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05862.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05862.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05862.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05868.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05868.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05868.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05869.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05869.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05869.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05871.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05871.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05871.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05882.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05882.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05882.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05889.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05889.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05889.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05891.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05891.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05891.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05895.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05895.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05895.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05899.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05899.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05899.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05905.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05905.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05905.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05915.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05915.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05915.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05917.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05917.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05917.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05919.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05919.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05919.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05922.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05922.webp",
    "ratio": 0.562,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05922.jpg"
  },
  {
    "src": "/fathopes/ranger-training/pux05927.jpg",
    "thumb": "/fathopes/_thumbs/ranger-training/pux05927.webp",
    "ratio": 1.778,
    "category": "Ranger Training",
    "catSlug": "ranger-training",
    "type": "image",
    "png": false,
    "name": "PUX05927.jpg"
  },
  {
    "src": "/fathopes/team-building/pux03523.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03523.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03523.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03537.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03537.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03537.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03563.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03563.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03563.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03575.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03575.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03575.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03603.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03603.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03603.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03611.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03611.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03611.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03616.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03616.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03616.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03639.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03639.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03639.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03645.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03645.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03645.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03653.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03653.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03653.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03657.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03657.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03657.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03681.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03681.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03681.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03727.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03727.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03727.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03740.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03740.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03740.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03741.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03741.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03741.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03749.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03749.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03749.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03756.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03756.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03756.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03760.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03760.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03760.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03765.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03765.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03765.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03774.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03774.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03774.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03779.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03779.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03779.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03790.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03790.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03790.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03800.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03800.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03800.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03807.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03807.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03807.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03809.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03809.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03809.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03824.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03824.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03824.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03874.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03874.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03874.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03922.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03922.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03922.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03931.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03931.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03931.JPG"
  },
  {
    "src": "/fathopes/team-building/pux03998.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux03998.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX03998.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04033.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04033.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04033.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04062.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04062.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04062.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04068.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04068.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04068.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04140.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04140.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04140.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04157.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04157.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04157.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04162.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04162.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04162.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04168.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04168.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04168.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04174.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04174.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04174.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04176.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04176.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04176.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04184.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04184.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04184.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04190.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04190.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04190.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04201.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04201.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04201.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04206.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04206.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04206.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04208.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04208.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04208.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04214.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04214.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04214.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04220.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04220.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04220.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04230.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04230.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04230.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04240.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04240.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04240.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04241.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04241.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04241.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04247.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04247.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04247.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04254.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04254.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04254.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04258.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04258.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04258.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04262.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04262.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04262.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04269.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04269.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04269.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04287.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04287.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04287.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04293.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04293.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04293.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04295.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04295.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04295.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04299.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04299.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04299.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04310.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04310.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04310.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04326.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04326.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04326.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04334.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04334.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04334.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04352.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04352.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04352.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04363.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04363.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04363.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04368.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04368.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04368.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04373.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04373.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04373.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04380.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04380.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04380.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04390.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04390.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04390.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04394.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04394.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04394.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04409.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04409.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04409.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04412.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04412.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04412.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04426.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04426.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04426.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04434.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04434.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04434.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04440.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04440.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04440.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04446.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04446.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04446.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04448.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04448.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04448.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04450.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04450.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04450.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04456.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04456.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04456.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04461.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04461.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04461.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04465.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04465.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04465.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04472.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04472.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04472.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04497.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04497.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04497.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04500.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04500.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04500.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04542.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04542.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04542.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04550.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04550.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04550.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04558.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04558.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04558.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04569.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04569.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04569.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04575.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04575.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04575.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04579.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04579.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04579.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04583.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04583.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04583.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04587.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04587.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04587.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04591.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04591.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04591.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04597.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04597.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04597.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04604.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04604.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04604.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04616.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04616.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04616.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04625.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04625.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04625.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04632.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04632.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04632.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04641.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04641.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04641.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04654.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04654.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04654.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04659.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04659.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04659.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04672.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04672.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04672.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04685.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04685.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04685.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04694.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04694.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04694.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04698.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04698.webp",
    "ratio": 0.562,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04698.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04727.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04727.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04727.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04754.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04754.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04754.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04773.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04773.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04773.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04779.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04779.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04779.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04784.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04784.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04784.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04790.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04790.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04790.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04796.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04796.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04796.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04800.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04800.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04800.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04805.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04805.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04805.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04813.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04813.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04813.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04825.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04825.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04825.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04829.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04829.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04829.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04835.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04835.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04835.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04840.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04840.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04840.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04846.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04846.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04846.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04850.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04850.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04850.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04856.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04856.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04856.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04862.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04862.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04862.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04881.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04881.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04881.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04884.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04884.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04884.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04894.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04894.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04894.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04902.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04902.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04902.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04921.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04921.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04921.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04927.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04927.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04927.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04965.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04965.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04965.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04972.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04972.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04972.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04986.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04986.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04986.JPG"
  },
  {
    "src": "/fathopes/team-building/pux04994.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux04994.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX04994.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05047.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05047.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05047.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05109.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05109.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05109.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05141.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05141.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05141.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05152.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05152.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05152.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05169.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05169.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05169.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05183.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05183.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05183.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05200.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05200.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05200.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05201.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05201.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05201.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05212.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05212.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05212.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05251.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05251.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05251.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05266.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05266.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05266.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05278.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05278.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05278.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05304.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05304.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05304.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05309.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05309.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05309.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05349.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05349.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05349.JPG"
  },
  {
    "src": "/fathopes/team-building/pux05360.jpg",
    "thumb": "/fathopes/_thumbs/team-building/pux05360.webp",
    "ratio": 1.778,
    "category": "Team Building",
    "catSlug": "team-building",
    "type": "image",
    "png": false,
    "name": "PUX05360.JPG"
  },
  {
    "src": "/fathopes/waste2energy/pux07095.jpg",
    "thumb": "/fathopes/_thumbs/waste2energy/pux07095.webp",
    "ratio": 1.778,
    "category": "Waste2Energy",
    "catSlug": "waste2energy",
    "type": "image",
    "png": false,
    "name": "PUX07095.jpg"
  },
  {
    "src": "/fathopes/waste2energy/pux07107.jpg",
    "thumb": "/fathopes/_thumbs/waste2energy/pux07107.webp",
    "ratio": 0.562,
    "category": "Waste2Energy",
    "catSlug": "waste2energy",
    "type": "image",
    "png": false,
    "name": "PUX07107.jpg"
  },
  {
    "src": "/fathopes/waste2energy/pux07117.jpg",
    "thumb": "/fathopes/_thumbs/waste2energy/pux07117.webp",
    "ratio": 1.778,
    "category": "Waste2Energy",
    "catSlug": "waste2energy",
    "type": "image",
    "png": false,
    "name": "PUX07117.jpg"
  },
  {
    "src": "/fathopes/waste2energy/pux07129.jpg",
    "thumb": "/fathopes/_thumbs/waste2energy/pux07129.webp",
    "ratio": 0.562,
    "category": "Waste2Energy",
    "catSlug": "waste2energy",
    "type": "image",
    "png": false,
    "name": "PUX07129.jpg"
  },
  {
    "src": "/fathopes/astro/pux02823.jpg",
    "thumb": "/fathopes/_thumbs/astro/pux02823.webp",
    "ratio": 0.562,
    "category": "Astro",
    "catSlug": "astro",
    "type": "image",
    "png": false,
    "name": "PUX02823.JPG"
  },
  {
    "src": "/fathopes/astro/pux02873.jpg",
    "thumb": "/fathopes/_thumbs/astro/pux02873.webp",
    "ratio": 0.562,
    "category": "Astro",
    "catSlug": "astro",
    "type": "image",
    "png": false,
    "name": "PUX02873.JPG"
  },
  {
    "src": "/fathopes/astro/pux02885.jpg",
    "thumb": "/fathopes/_thumbs/astro/pux02885.webp",
    "ratio": 0.562,
    "category": "Astro",
    "catSlug": "astro",
    "type": "image",
    "png": false,
    "name": "PUX02885.JPG"
  },
  {
    "src": "/fathopes/plus-community-day/pux02274.jpg",
    "thumb": "/fathopes/_thumbs/plus-community-day/pux02274.webp",
    "ratio": 1.778,
    "category": "PLUS Community Day",
    "catSlug": "plus-community-day",
    "type": "image",
    "png": false,
    "name": "PUX02274.JPG"
  },
  {
    "src": "/fathopes/mitsui-x-fathopes-energy/pux03432.jpg",
    "thumb": "/fathopes/_thumbs/mitsui-x-fathopes-energy/pux03432.webp",
    "ratio": 1.778,
    "category": "Mitsui X FatHopes Energy",
    "catSlug": "mitsui-x-fathopes-energy",
    "type": "image",
    "png": false,
    "name": "PUX03432.jpg"
  },
  {
    "src": "/fathopes/klb-fuel/20260514-114622-jpg.jpeg",
    "thumb": "/fathopes/_thumbs/klb-fuel/20260514-114622-jpg.webp",
    "ratio": 0.75,
    "category": "KLB Fuel",
    "catSlug": "klb-fuel",
    "type": "image",
    "png": false,
    "name": "20260514_114622.jpg.jpeg"
  },
  {
    "src": "/fathopes/my-aero-2026/my-aero-backdrop.jpg",
    "thumb": "/fathopes/_thumbs/my-aero-2026/my-aero-backdrop.webp",
    "ratio": 1.612,
    "category": "My Aero 2026",
    "catSlug": "my-aero-2026",
    "type": "image",
    "png": false,
    "name": "My-Aero_Backdrop.jpg"
  },
  {
    "src": "/fathopes/turiya-earth-day-2026/26cc38f4-4534-4a41-84cf-2db4029229fe.jpg",
    "thumb": "/fathopes/_thumbs/turiya-earth-day-2026/26cc38f4-4534-4a41-84cf-2db4029229fe.webp",
    "ratio": 0.75,
    "category": "Turiya Earth Day 2026",
    "catSlug": "turiya-earth-day-2026",
    "type": "image",
    "png": false,
    "name": "26cc38f4-4534-4a41-84cf-2db4029229fe.JPG"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/1080-x-1080.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/1080-x-1080.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "1080 x 1080.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/activate-dormant-recyclers-100.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/activate-dormant-recyclers-100.webp",
    "ratio": 2,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Activate Dormant Recyclers-100.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/cash.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/cash.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Cash.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/deals.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/deals.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Deals.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/download.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/download.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Download.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/drop-off-2.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/drop-off-2.webp",
    "ratio": 1.984,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Drop Off.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/drop-off.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/drop-off.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Drop-off.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/fa-60cm-round-matte-sticker.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/fa-60cm-round-matte-sticker.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "FA-60cm-Round-Matte-Sticker.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/incentives.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/incentives.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Incentives.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/income.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/income.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Income.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/koppiku-app-banner.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/koppiku-app-banner.webp",
    "ratio": 2,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Koppiku-App Banner.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/koppiku.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/koppiku.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "koppiku.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/ranger-sign-up-100.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/ranger-sign-up-100.webp",
    "ratio": 1.996,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Ranger Sign Up -100.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/rewards-banner-100.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/rewards-banner-100.webp",
    "ratio": 1.998,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Rewards Banner -100.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/rewards-catalogues.jpg",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/rewards-catalogues.webp",
    "ratio": 1.984,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": false,
    "name": "Rewards Catalogues.jpg"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/saf.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/saf.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "SAF.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/spot-icon-20x20.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/spot-icon-20x20.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Spot-Icon-20x20.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/supporthotline.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/supporthotline.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "SupportHotline.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/uco.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/uco.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "UCO.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/uniform.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/uniform.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Uniform.png"
  },
  {
    "src": "/fathopes/fathopes-loyalty-app/vouchers.png",
    "thumb": "/fathopes/_thumbs/fathopes-loyalty-app/vouchers.webp",
    "ratio": 1,
    "category": "FatHopes Loyalty App",
    "catSlug": "fathopes-loyalty-app",
    "type": "image",
    "png": true,
    "name": "Vouchers.png"
  },
  {
    "src": "/fathopes/bunting/flyer-a4-fa.png",
    "thumb": "/fathopes/_thumbs/bunting/flyer-a4-fa.webp",
    "ratio": 0.706,
    "category": "Bunting",
    "catSlug": "bunting",
    "type": "image",
    "png": true,
    "name": "Flyer-A4-FA.png"
  },
  {
    "src": "/fathopes/corporate-asset/googlebackground.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/googlebackground.webp",
    "ratio": 1.778,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "GoogleBackground.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/laptopwallpaper-01.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/laptopwallpaper-01.webp",
    "ratio": 1.778,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "LaptopWallpaper-01.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/laptopwallpaper-02.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/laptopwallpaper-02.webp",
    "ratio": 1.778,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "LaptopWallpaper-02.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/linkedin-profilebanner-02.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/linkedin-profilebanner-02.webp",
    "ratio": 3.622,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "Linkedin-ProfileBanner-02.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/linkedin-profilebanner.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/linkedin-profilebanner.webp",
    "ratio": 3.622,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "Linkedin-ProfileBanner.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/mobilewallpaper-01.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/mobilewallpaper-01.webp",
    "ratio": 0.562,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "MobileWallpaper-01.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/mobilewallpaper-02.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/mobilewallpaper-02.webp",
    "ratio": 0.562,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "MobileWallpaper-02.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/mobilewallpaper-03.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/mobilewallpaper-03.webp",
    "ratio": 0.562,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "MobileWallpaper-03.jpg"
  },
  {
    "src": "/fathopes/corporate-asset/mobilewallpaper-04.jpg",
    "thumb": "/fathopes/_thumbs/corporate-asset/mobilewallpaper-04.webp",
    "ratio": 0.562,
    "category": "Corporate Asset",
    "catSlug": "corporate-asset",
    "type": "image",
    "png": false,
    "name": "MobileWallpaper-04.jpg"
  },
  {
    "src": "/fathopes/brand-video/episode-1.mp4",
    "thumb": "/fathopes/brand-video/episode-1.mp4",
    "ratio": 1.778,
    "category": "Brand Video",
    "catSlug": "brand-video",
    "type": "video",
    "png": false,
    "name": "EPISODE 1.mp4"
  },
  {
    "src": "/fathopes/ai-video/identity.mp4",
    "thumb": "/fathopes/ai-video/identity.mp4",
    "ratio": 1.778,
    "category": "AI Video",
    "catSlug": "ai-video",
    "type": "video",
    "png": false,
    "name": "Identity.mp4"
  },
  {
    "src": "/fathopes/fathopes-vendor-app/vendor-app-guide.mp4",
    "thumb": "/fathopes/fathopes-vendor-app/vendor-app-guide.mp4",
    "ratio": 1.778,
    "category": "FatHopes Vendor App",
    "catSlug": "fathopes-vendor-app",
    "type": "video",
    "png": false,
    "name": "Vendor App-Guide.mp4"
  }
];
